.TH "md__r_e_a_d_m_e" 3 "Wed Oct 3 2018" "Version 0.1" ""To be or..." genetic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Python 

.SS "Executing this script will give following output"
.PP
Fit value for iteration: 1357
.IP "1." 4
42\&.0 To be or not to be\&.\&.\&.
.IP "2." 4
40\&.5 TowbE or not to be\&.\&.\&.
.IP "3." 4
40\&.0 To be or not to be\&.\&.
.IP "4." 4
40\&.0 To be or not to be\&.\&.
.IP "5." 4
40\&.0 To be or not to be\&.\&.
.IP "6." 4
40\&.0 To be or not to be\&.\&.
.PP
.PP
42\&.0 To be or not to be\&.\&.\&.
.PP
\fC\fP.PP
More details in \fCdocumentation\fP 
